### ISSUE TITLE
Tests are failing on Ubuntu 22.04 and 20.04 with python 3.10 and 3.8 correspondingly

### ISSUE THREAD

**Issue by antonsoroko** [pwr-Solaar/Solaar#3083]
Tests are failing on Ubuntu 22.04 and 20.04 with python 3.10 and 3.8 correspondingly.
I do not know if it is expected or not - i just got emails from PPA and decided to highlight this.
If it is expected from this repo point of view - then ok. Nothing can be done on ppa side regarding that.

https://launchpadlibrarian.net/838408047/buildlog_ubuntu-jammy-amd64.solaar_1.1.18+202512182049~ubuntu22.04.1_BUILDING.txt.gz
https://launchpadlibrarian.net/838407884/buildlog_ubuntu-focal-amd64.solaar_1.1.18+202512182049~ubuntu20.04.1_BUILDING.txt.gz
```
=================================== FAILURES ===================================
_ test_notification_flag_str[NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY-link quality\n               mouse extra buttons] _

flag_bits = <NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY: 525312>
expected_names = 'link quality\n               mouse extra buttons'

    @pytest.mark.parametrize(
        "flag_bits, expected_names",
        [
            (None, ""),
            (hidpp10_constants.NotificationFlag(0x0), "none"),
            (hidpp10_constants.NotificationFlag(0x001000), "multi touch"),
            (hidpp10_constants.NotificationFlag(0x080000), "mouse extra buttons"),
            (
                hidpp10_constants.NotificationFlag(0x080400),
                ("link quality\n               mouse extra buttons"),
            ),
        ],
    )
    def test_notification_flag_str(flag_bits, expected_names):
>       flag_names = hidpp10_constants.flags_to_str(
            hidpp10_constants.NotificationFlag(flag_bits) if flag_bits is not None else None, fallback="none"
        )

tests/logitech_receiver/test_hidpp10.py:292: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
logitech_receiver/hidpp10_constants.py:120: in flags_to_str
    flag_names = NotificationFlag.flag_names(flags)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <enum 'NotificationFlag'>
flags = <NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY: 525312>

    @classmethod
    def flag_names(cls, flags) -> List[str]:
        """Extract the names of the flags from the integer."""
>       return flags.name.replace("_", " ").lower().split("|")
E       AttributeError: 'NoneType' object has no attribute 'replace'

logitech_receiver/hidpp10_constants.py:94: AttributeError
=============================== warnings summary ===============================
../../../../../../usr/lib/python3/dist-packages/evdev/eventio_async.py:89
  /usr/lib/python3/dist-packages/evdev/eventio_async.py:89: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def __anext__(self):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/logitech_receiver/test_hidpp10.py::test_notification_flag_str[NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY-link quality\n               mouse extra buttons]
============= 1 failed, 630 passed, 30 skipped, 1 warning in 2.24s =============
E: pybuild pybuild:369: test: plugin distutils failed with: exit code=1: cd '/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10/build'; python3.10 -m pytest tests
dh_auto_test: error: pybuild --test --test-pytest -i python{version} -p 3.10 returned exit code 13
make: *** [debian/rules:13: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2025-12-18T20:56:04Z

Finished
--------
```

**Comment by pfps** [comment]
I don't know if "expected" is the right word to use, but the tests work fine on Python 3.13.

**Comment by antonsoroko** [comment]
i mean -i saw that they work fine on 3.13 :-) that's why i specified that the issue reproduces on python 3.10 and 3.8.
the question is - do you want tests to work on old python or not.
if no - then nothing to do.
if yes - then i guess some fixes should be made, if it is even possible.

**Comment by pfps** [comment]
It would be nice for the tests to work in 3.8.

**Comment by pfps** [comment]
I don't know why that one test is failing in Python 3.8 and 3.10.  It's an edge case that should not show up in actual use.  I've commented it out in PR #3091 and will merge that in so that the testing doesn't fail in older Pythons.

**Comment by pfps** [comment]
Let me know if there are problems with this change merged in.

**Comment by antonsoroko** [comment]
@pfps ok. to make a real test (in PPA) we would need to wait for a new version (tag).

**Comment by pfps** [comment]
Is there still a PPA that tracks all updates to Solaar?

**Comment by antonsoroko** [comment]
@pfps i disabled it since it breaks too often because of often changes to `setup` files. those files are patched by debian build scripts (probably you use some non-standard or non-compliant setup configuration) and when you make changes to those files - debian maintainer needs to update patches. but they do it only during release, since otherwise they will be buried with such "update patches" work. see https://salsa.debian.org/debian/solaar/-/tree/debian/latest/debian/patches?ref_type=heads and https://github.com/pwr-Solaar/Solaar/issues/2186#issuecomment-1964403079

about "non-standard or non-compliant setup configuration" - maybe @skitt can give some clarifications why those patched are needed and why not to make chances in this repo.
imho, ideally it would be to change setup files in this repo to be compliant with debian build system - so then nobody would need to create/update patches.

**Comment by skitt** [comment]
The reason the remaining patches are in Debian only is because they are Debian-specific:

* `remove-udev-check.patch` removes the rule check because we know the package installs the file (and doesn’t necessarily use the upstream name)
* `restore-requirements.patch` was an attempt at getting the Python `debhelper` build plugin to add appropriate dependencies; it’s not appropriate for other distributions
* `skip-udev-rule-installation.patch` relies on the Debian package build tools to install the rule file wherever appropriate
* `udev-plugdev.patch` relies on a maintainer-script-controlled file to decide whether to use `plugdev`

I think the package setup in the main repository should be OK as-is, but as you say @antonsoroko it is liable to break because of other changes to Solaar and it’s a pain to have to deal with them on the fly (as would be the case for a “build packages for every commit” setup).

**Comment by antonsoroko** [comment]
Thanks for the detailed answer!

"Unstable" ppa will remain disabled for the reasons described above.

**Comment by antonsoroko** [comment]
@pfps looks like the same tests are still failing:
```
=================================== FAILURES ===================================
_ test_notification_flag_str[NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY-link quality\n               mouse extra buttons] _

flag_bits = <NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY: 525312>
expected_names = 'link quality\n               mouse extra buttons'

    @pytest.mark.parametrize(
        "flag_bits, expected_names",
        [
            # doesn't work in Python 3.8 and 3.10 for some reason        (None, ""),
            (hidpp10_constants.NotificationFlag(0x0), "none"),
            (hidpp10_constants.NotificationFlag(0x001000), "multi touch"),
            (hidpp10_constants.NotificationFlag(0x080000), "mouse extra buttons"),
            (
                hidpp10_constants.NotificationFlag(0x080400),
                ("link quality\n               mouse extra buttons"),
            ),
        ],
    )
    def test_notification_flag_str(flag_bits, expected_names):
>       flag_names = hidpp10_constants.flags_to_str(
            hidpp10_constants.NotificationFlag(flag_bits) if flag_bits is not None else None, fallback="none"
        )

tests/logitech_receiver/test_hidpp10.py:292: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
logitech_receiver/hidpp10_constants.py:120: in flags_to_str
    flag_names = NotificationFlag.flag_names(flags)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <enum 'NotificationFlag'>
flags = <NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY: 525312>

    @classmethod
    def flag_names(cls, flags) -> List[str]:
        """Extract the names of the flags from the integer."""
>       return flags.name.replace("_", " ").lower().split("|")
E       AttributeError: 'NoneType' object has no attribute 'replace'

logitech_receiver/hidpp10_constants.py:94: AttributeError
=============================== warnings summary ===============================
../../../../../../usr/lib/python3/dist-packages/evdev/eventio_async.py:89
  /usr/lib/python3/dist-packages/evdev/eventio_async.py:89: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def __anext__(self):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/logitech_receiver/test_hidpp10.py::test_notification_flag_str[NotificationFlag.MOUSE_EXTRA_BUTTONS|LINK_QUALITY-link quality\n               mouse extra buttons]
============= 1 failed, 629 passed, 30 skipped, 1 warning in 2.08s =============
```
https://launchpadlibrarian.net/842463923/buildlog_ubuntu-jammy-amd64.solaar_1.1.19+202601082133~ubuntu22.04.1_BUILDING.txt.gz
https://launchpadlibrarian.net/842463875/buildlog_ubuntu-focal-amd64.solaar_1.1.19+202601082133~ubuntu20.04.1_BUILDING.txt.gz

**Comment by pfps** [comment]
This is due to a change in the Flags part of Enum.   See #3107.

**Comment by pfps** [comment]
Is this still a problem with the version of Solaar in this repository?

**Comment by pfps** [comment]
I think the problem is known, but I forget whether the solution has been merged.

**Comment by antonsoroko** [comment]
@pfps  https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable
as of 2 March 2026 with version 1.1.19 - there is still a problem with old python, as you can see (red icons for old Ubuntu distros).

**Comment by antonsoroko** [comment]
@pfps nice to see a fix. when the new version will be releases launchpad ppa will build new version and we will see if the issue is gone for old ubuntu.

**Comment by antonsoroko** [comment]
@pfps with 1.1.20 tests are failing again with old python
https://launchpadlibrarian.net/866752126/buildlog_ubuntu-focal-amd64.solaar_1.1.20+202606281618~ubuntu20.04.1_BUILDING.txt.gz
```
==================================== ERRORS ====================================
_ ERROR collecting .pybuild/cpython3_3.8/build/tests/logitech_receiver/test_base.py _
/usr/lib/python3/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8/build/tests/logitech_receiver/test_base.py", line 338
E       mock.patch.object(base.hidapi, "write") as mock_write,
E                                               ^
E   SyntaxError: invalid syntax
_ ERROR collecting .pybuild/cpython3_3.8/build/tests/logitech_receiver/test_device.py _
tests/logitech_receiver/test_device.py:56: in <module>
    class DeviceInfoStub:
tests/logitech_receiver/test_device.py:65: in DeviceInfoStub
    centurion_report_id: int | None = None
E   TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
------------------------------- Captured stderr --------------------------------
```

i can simply disable builds for old ubuntu versions.
or if you have desire to support old python - you can fix this. i am not sure if it makes sense or not to support old python.

but please let me know your decision.
