### PR TITLE
GUI for changing Notification Rules

### PR DESCRIPTION
**Pull request by viniciusbm**
See discussion in #988.

This PR adds a GUI to display, create and edit diversion rules. It still needs to be improved in many ways, but it's already functional. It displays built-in rules (read-only) and rules defined by the user (which are editable). To see the available options, right-click a row. To edit the contents of a row, click it and change the values on the bottom panel. For types that require a string from a list, suggestions are shown under the text field in a case-insensitive way, ignoring underscores and spaces, considering any allowed value that contains the input text as a substring at any position (e.g. for `KeyPress`, typing "volume" shows the suggestions `XF86_AudioLowerVolume` and `XF86_AudioRaiseVolume`).

TESTING SUGGESTIONS:  
Before testing, read docs/rules.md so that you understand something about what these rules do in Solaar.  Create the file ~/.config/solaar/rules.yaml with a few rules.  There are some sample rules at the end of docs/rules.md
Then click on the button for editing rules.  Check that all your rules show up and that the built-in rules also show up.  Report on any problems.
Then try to edit some rules.  Do some easy changes, like changing a KeyPress or MouseScroll action or a Test condition.  Do some structural changes, like adding a condition to a rule or adding an entirely new rule.  Check that these rules are saved correctly. Report on any problems.
Suggestions for UI changes are welcome.  Changes that are hard to implement will likely be deferred to some indefinite future.

### CODE REVIEW

**Comment by pfps** [comment]
The commit for MouseClick looks ready to be added to Solaar.  Can you read a PR with just that commit?

**Comment by pfps** [comment]
One advantage of YAML is that it can be much nicer-looking than JSON.  That doesn't matter if people aren't writing and reading the file.  So I'm not worried that the file might not look so nice once if it has been written by a program.   

That said, it's nice to have nice-looking files.  Is that what the third commit is for?

**Comment by pfps** [comment]
A few GUI comments.

The button to open the rule editor belongs on the bottom row, but probably on the right where it is separated from the other two buttons.

The save and discard buttons on the rule window take up a lot of space.  Can they be placed on the top or bottom instead?

When typing in new values there should be some sort of indication that the value is not suitable.  For example, I changed the name of a test.  Solaar produced warnings but nothing showed in the GUI.  Ideally there should be a selection box so that you don't have to type in but can select.  This may require some refactoring of the rules (so that named rules and list rules are separated, for example).

**Comment by pfps** [comment]
Exposing the hex values of features, etc., is probably not needed.

**Comment by pfps** [comment]
The box for entering new values appears to be fixed size and is too small to fit the values.
There is lots of blank space in the "data entry" area.  This should probably be eliminated, and all excess space given to the rule display area.

**Comment by pfps** [comment]
The key-entry interface is quite nice.  The only extra possible thing to add would be to allow for deleting any key in the sequence.

Using part of that interface for entering test names seems like a good idea.

**Comment by pfps** [comment]
The structural editing interface looks OK, but I'm not a GUI designer.

**Comment by viniciusbm** [comment]
> That said, it's nice to have nice-looking files. Is that what the third commit is for?

Partially, yes. The file wouldn't look good regardless of the value of `default_flow_style`: either it would have very long lines with many delimiters or everything would be shown nested, which can be confusing especially for `MouseScroll`: 
```
- MouseScroll:
    - -1
    - 0
```

That commit also fixes a bug in the GUI code: it didn't show correctly rules that don't have an explicit `Rule`, such as the ones from the example.

**Comment by pfps** [comment]
There really should be a pretty-printer for YAML that tries to be compact but not make long lines.  :-1:

**Comment by viniciusbm** [comment]
> There really should be a pretty-printer for YAML that tries to be compact but not make long lines. -1

The way I did it (by creating a subclass of `list` with a custom `representer`) allows us to change the behaviour of the YAML library when it saves the file, even though the Python code doesn't look nice. Currently, it prints in a single line only lists that contain only int, float and str, without children; also, singleton lists that contain a string are replaced by the string itself, without the brackets, since the classes you implemented already support that.

**Comment by pfps** [comment]
> > There really should be a pretty-printer for YAML that tries to be compact but not make long lines. -1
> 
> The way I did it (by creating a subclass of `list` with a custom `representer`) allows us to change the behaviour of the YAML library when it saves the file, even though the Python code doesn't look nice. Currently, it prints in a single line only lists that contain only int, float and str, without children; also, singleton lists that contain a string are replaced by the string itself, without the brackets, since the classes you implemented already support that.

OK, that looks right.

**Comment by viniciusbm** [comment]
Sorry for the forced pushes without new content. Pre-commit shows no error for me locally, but the remote execution of flake8 is showing a weird error: 
`lib/logitech_receiver/diversion.py:521:1: F811 redefinition of unused 'MouseClick' from line 491`

But line 521 is the definition of another class, which has nothing to do with `MouseClick`. Also, this error began at 840668b, which did not change anything on this part of the code. :thinking:

**Comment by viniciusbm** [comment]
> Pre-commit shows no error for me locally, but the remote execution of flake8 is showing a weird error.

I don't know why, but apparently flake8 was analysing the files created by applying the changes of this PR to the files in master. After merging and removing the duplication (which didn't exist in my local files), the error is gone.

---

@pfps, thank you for your feedback. I've made the changes you suggested:

> The button to open the rule editor belongs on the bottom row, but probably on the right where it is separated from the other two buttons.

I moved the button to the right. 

> The save and discard buttons on the rule window take up a lot of space. Can they be placed on the top or bottom instead?

I moved that panel to the top.

> When typing in new values there should be some sort of indication that the value is not suitable. For example, I changed the name of a test. Solaar produced warnings but nothing showed in the GUI. Ideally there should be a selection box so that you don't have to type in but can select.

I added a warning icon when the value is not suitable. Also, I added a drop-down list to the fields that don't have too many values.  

> Exposing the hex values of features, etc., is probably not needed.

I removed the labels that used to show the hex values.

> The box for entering new values appears to be fixed size and is too small to fit the values.
There is lots of blank space in the "data entry" area. This should probably be eliminated, and all excess space given to the rule display area.

I made the fields bigger. Do you think they're large enough now?

> The key-entry interface is quite nice. The only extra possible thing to add would be to allow for deleting any key in the sequence.

I added a delete button for every key in `KeyPress` and every argument in `Execute`.

**Comment by pfps** [comment]
It's looking much better.

I'm still seeing a lot of extra vertical space for the edit region and too little space for the key edit box.  See the attached image.

I really like how you can enter any feature, but only some are shown.  Would it be possible to show matches against any feature when none of the originally shown ones match?   For example, once one types "MU" the match would be "MULTIPLATFORM".  If this is hard though, don't worry about it.

I have a rule for LOWRES WHEEL, which is not in the completion list.  When I click on the feature, the box value shows the one from the previous feature value being shown.

A couple of display changes.  I think that this should be advertised as rules, and the HID++ and Diversion phrases deemphasized in the GUI.  So "Solaar Rule Editor" might be best for the window title and "Rule Editor" for the button.  (I'm not all that keen on these names, just that I think they are better than the current ones.)  See if you can think of something better.

I think this is very close to ready for testing by others.
Screenshot_2020-11-14_13-41-05

**Comment by pfps** [comment]
Pre-commits use some sot of magic that I don't understand completely.  The easiest thing that I've found to do is to rebase to the current version of master before uploading changes.

**Comment by viniciusbm** [comment]
> I'm still seeing a lot of extra vertical space for the edit region and too little space for the key edit box. See the attached image.

I made the bottom panel shorter, since no features used the old height completely. Regarding the entry width, I think it's affected by the system DPI setting. I changed the minimum width of the `KeyPress` entry to 30% of the window width. If you think it's better this way, I can change the other sizes to relative values as well (and listen for a signal to update the size when the window is resized). 

> I really like how you can enter any feature, but only some are shown. Would it be possible to show matches against any feature when none of the originally shown ones match? For example, once one types "MU" the match would be "MULTIPLATFORM". If this is hard though, don't worry about it.

That's very easy: the list of possible matches and the list of items shown on the drop-down list are created separately. Done.
Of course, if a feature is known to do something useful using diversion, we can add it to the drop-down list. 

> I have a rule for LOWRES WHEEL, which is not in the completion list. When I click on the feature, the box value shows the one from the previous feature value being shown.

Fixed.

> A couple of display changes. I think that this should be advertised as rules, and the HID++ and Diversion phrases deemphasized in the GUI. So "Solaar Rule Editor" might be best for the window title and "Rule Editor" for the button. (I'm not all that keen on these names, just that I think they are better than the current ones.) See if you can think of something better.

I changed the names to the ones you suggested, as I can't think of anything better. However, if diversion and HID++ aren't shown to the users, maybe they will think that the rules can be used with any feature. Also, some features may or may not use diversion according to the settings (such as `REPROG CONTROLS V4`). I don't know how to make the distinction clear without using the technical terms, but I agree that it's better if things are clear without them. 

---

I've been pushing several small commits, but I can squash them later if you want.

**Comment by pfps** [comment]
It's fine having lots of commits. 

Another nit:  when closing the rule editor the close dialog is a bit confusing.  If I made changes and had done "Save changes" and hadn't made any more changes, what is the close dialog about?  Are the saved changes *not* permanent?

**Comment by viniciusbm** [comment]
> Another nit: when closing the rule editor the close dialog is a bit confusing. If I made changes and had done "Save changes" and hadn't made any more changes, what is the close dialog about? Are the saved changes not permanent?

In that case, the close dialogue isn't supposed to be shown. If it is shown, there must be some bug (probably the variable that tells whether the file has unsaved changes is being incorrectly set to True when the user does something that doesn't change any values).

**Comment by pfps** [comment]
Something is definitely wrong.  The save and close buttons are greyed out but I'm getting the close dialog.  It looks as if discard changes greys out the buttons but doesn't turn off the close dialog (and I think it should).

**Comment by viniciusbm** [comment]
> Something is definitely wrong. The save and close buttons are greyed out but I'm getting the close dialog. It looks as if discard changes greys out the buttons but doesn't turn off the close dialog (and I think it should).

The dialogue was showing after discarding changes, and I've fixed it now. Thanks for letting me know.

You previously said that it was also happening after **saving** changes, but I cannot reproduce that. Maybe some of the components are incorrectly calling `on_update()`. I'll keep on investigating.

**Comment by pfps** [comment]
I guess that I was confusing saving and discarding changes.   I'll let you know if I see any more anomalies.

**Comment by pfps** [comment]
This PR still has the MouseClicks commit, but it might be empty.
You should remove the commit from this PR.  There is a way to do this with rebase using the command described in https://sethrobertson.github.io/GitFixUm/fixup.html#remove_deep

Make sure that you can recover in case something goes wrong!

The last two commits have the same description.  Please change one of them.

**Comment by viniciusbm** [comment]
> The last two commits have the same description. Please change one of them.

Done. The duplicated name was introduced when I was fixing a pre-commit error and amended a commit with the message of another one. 

> This PR still has the MouseClicks commit, but it might be empty.
> You should remove the commit from this PR. 

I did what that website suggests, and it helped to make the graph (```git log --graph```) linear again, without 'merge' commits. However, GitHub would still show the commit here. I think it's right now, after I rebased it to the latest master commit.

**Comment by pfps** [comment]
The commits look good now, thanks.

**Comment by pfps** [comment]
@barolo @sk8geek  This PR is ready for testing.  See the testing suggestions in the first comment.

**Comment by sk8geek** [comment]
Hi, struggling with this, perhaps I'm doing something wrong?  I cloned from `git@github.com:viniciusbm/Solaar.git` but when I run `solaar` I get
```
solaar: error: Traceback (most recent call last):
  File "/home/steven/Solaar/lib/solaar/gtk.py", line 153, in main
    import solaar.listener as listener
  File "/home/steven/Solaar/lib/solaar/listener.py", line 32, in <module>
    from logitech_receiver import notifications as _notifications
  File "/home/steven/Solaar/lib/logitech_receiver/notifications.py", line 30, in <module>
    from . import diversion as _diversion
  File "/home/steven/Solaar/lib/logitech_receiver/diversion.py", line 27, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```
I tried to install `psutil` with `pip install psutil` but that results in 2.5 screens full of errors. It looks like the root cause might be:
```
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
        9 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by pfps** [comment]
It looks as if the pip install of psutil requires lots of development stuff.   
Try 
```
sudo apt-get update -y 
sudo apt-get install -y python-psutil
``` 
instead.

**Comment by sk8geek** [comment]
Thanks (I'm Fedora, so dnf rather than apt) However, install python-psutil worked but `solaar` then gave another error relating to Xlib so installed that. Now it's complaining about `pynput` which seems to be `pip install pynput` but that just results in a load of errors, root cause seems to be:
```
    evdev/input.c:10:10: fatal error: Python.h: No such file or directory
       10 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by pfps** [comment]
You should be able to install these packages without needing to compile anything, at least in Fedora - I'm running Fedora 33.

Please try 
```
pip install --user evdev
```

**Comment by pfps** [comment]
If that doesn't work you could install Python development via:
```
sudo dnf install gcc python3-devel
```

**Comment by sk8geek** [comment]
Thanks, needed the gcc/python3-devel command, then pynput but that fixes things. On MX Keys I find that backlight, Fx Swap and Caps Lock enable/disable work.  On Pebble mouse I find sensitivity change has effect.  Also `~/.config/solaar/config.json` was created and seemed to pick up mouse/keyboard correctly.

**Comment by pfps** [comment]
Excellent.  Try editing the rules using the new button at the bottom of the main window.  I think you can copy a built-in rule to create a new rule.  Then see whether ~/.config/solaar/rules.yaml shows up and looks reasonable.

**Comment by sk8geek** [comment]
Not sure where you mean? In "MK Keys" (should be MX Keys) I have a control that I've not seen before - Key/Button Diversion - but I don't have anything that I'd describe as "at the bottom of the main window"?

**Comment by pfps** [comment]
This PR adds the ability to edit the notification rules by pressing the "Rule Editor" button on the bottom right of the main window.   That should pop up a new window with the four built-in rules showing.  You can copy one of them and then add the copy as a new user-defined rule.

**Comment by pfps** [comment]
I'm going to add the name fix for MK Keys to a different PR that should be merged in soon.

**Comment by sk8geek** [comment]
solaar

Am I looking in the wrong place? Not got the right version? Thanks

**Comment by pfps** [comment]
I expect you have the wrong PR.

To get this PR the first time
```
git fetch origin pull/998/head:pull_998
git checkout pull_998
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_998
git fetch origin pull/998/head
git reset --hard FETCH_HEAD
```

**Comment by sk8geek** [comment]
Cool, yes, wrong branch. Did all that, got the Rule button, copied a rule and the yaml file was created.  (Not sure how rules are meant to work and don't want to mess up my keyboard.)

**Review by pfps — APPROVED** [review]
Looks good to me, and has some testing.

**Comment by TomParis01** [comment]
Could you add the already implemented [CHANGE_HOST](https://github.com/pwr-Solaar/Solaar/pull/844) function to the GUI? Right now I execute the solaar CLI in the GUI instead

**Comment by pfps** [comment]
It should be in the GUI.  If not, please provide a screen shot and the output of `solaar show`.
