### ISSUE TITLE
Problem with gtk4 loaded?

### ISSUE THREAD

**Issue by satmandu** [pwr-Solaar/Solaar#1050]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
``` 
solaar -V
solaar 1.0.4
```
- Distribution: Chromebrew
- Kernel version (ex. `uname -srmo`): ```
Linux localhost 4.4.241-19420-g5a63ca2874a0 #1 SMP PREEMPT Mon Jan 11 21:31:52 PST 2021 x86_64 GNU/Linux```
- Output of `solaar show`:
```
solaar show
/usr/local/lib/python3.9/site-packages/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
solaar: error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 190, in run
    c = list(_receivers(hidraw_path))
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 97, in _receivers
    from logitech_receiver import Receiver
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 26, in <module>
    from solaar.ui import notify as _notify
  File "/usr/local/lib/python3.9/site-packages/solaar/ui/__init__.py", line 31, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/local/lib/python3.9/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 4.0

```

Solaar does not appear to load with gtk4 installed.
```
solaar probe
/usr/local/lib/python3.9/site-packages/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
solaar: error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 190, in run
    c = list(_receivers(hidraw_path))
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 97, in _receivers
    from logitech_receiver import Receiver
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 26, in <module>
    from solaar.ui import notify as _notify
  File "/usr/local/lib/python3.9/site-packages/solaar/ui/__init__.py", line 31, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/local/lib/python3.9/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 4.0
```

Previously I got this before updating python-gobjects to git-current:
```
solaar probe
solaar: error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 190, in run
    c = list(_receivers(hidraw_path))
  File "/usr/local/lib/python3.9/site-packages/solaar/cli/__init__.py", line 97, in _receivers
    from logitech_receiver import Receiver
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/__init__.py", line 36, in <module>
    from . import listener, status  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/listener.py", line 28, in <module>
    from . import base as _base
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base.py", line 35, in <module>
    from .base_usb import ALL as _RECEIVER_USB_IDS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/base_usb.py", line 32, in <module>
    from .descriptors import DEVICES as _DEVICES
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/descriptors.py", line 27, in <module>
    from .settings_templates import FeatureSettings as _FS
  File "/usr/local/lib/python3.9/site-packages/logitech_receiver/settings_templates.py", line 26, in <module>
    from solaar.ui import notify as _notify
  File "/usr/local/lib/python3.9/site-packages/solaar/ui/__init__.py", line 27, in <module>
    from gi.repository import GLib, Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/local/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/local/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/local/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
```

**Comment by pfps** [comment]
I don't have access to GTK 4, so this might be hard to fix.  However, there is a recent change to Solaar that affects this part of the code that was done after 1.0.4.  So please clone this repository and run Solaar from the cloned directory (as `bin/solaar`).   That  might fix your problem.   Report back on success (or failure).

For more information see https://pwr-solaar.github.io/Solaar/installation

**Comment by pfps** [comment]
Closing due to no response from submitter.

**Comment by ey3ball** [comment]
Just for the record, I was having that issue with 1.0.4 it seems to be working fine with 1.1.1
