### ISSUE TITLE
Ubuntu 22.10's upgrade to 1.1.5 broke stuff. ("'NoneType' object is not iterable") w/fix

### ISSUE THREAD

**Issue by fat-tire** [pwr-Solaar/Solaar#1785]
Hey fwiw in Ubuntu 22.10 (beta), I just got an upgrade of solaar from 1.1.1 to 1.1.5 ([solaar_1.1.5+dfsg-1_all.deb](https://packages.ubuntu.com/kinetic/solaar)) and noticed that solaar was now broken.  Running it manually resulted in an error that ended like this:

```
....
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 352, in persister
    self._persister = _configuration.persister(self)
  File "/usr/share/solaar/lib/solaar/configuration.py", line 214, in persister
    _load()
  File "/usr/share/solaar/lib/solaar/configuration.py", line 71, in _load
    _config = _cleanup_load(loaded_config)
  File "/usr/share/solaar/lib/solaar/configuration.py", line 137, in _cleanup_load
    for element in c:
TypeError: 'NoneType' object is not iterable
```

This was running as the user (not rute) and seemed to be an issue parsing the `~/.config/solaar/config.yaml` file.  When I looked at that file, it was completely blank, though there was a file there `config.json` modified five months back that looked like this:

```
{
  "_version": "1.1.1"
}
```

On a hunch, I set the blank `config.yaml` to instead look like:

```
_version:1.1.5
```

and started solar and it came back!  It repopulated the config.yaml, so I'm guessing it just wanted any values in there so it wouldn't error out.

While this is probably a bug w/ubuntu's packaging and may even be due to me running as a normal user, the `configuration.yaml` file's `_cleanup_load(c)` function should probably gracefully behave if there are no yaml entries in there rather than silently crashing.

That is all!  This is probably going to have to also be addressed in the Ubuntu release, but I figured this was upstream so maybe it should be here as well.  Thanks!

**Comment by pfps** [comment]
This looks rather weird.  I don't see where the code could produce the empty yaml file.  I'll create a patch for the problem though.

One thing.  Solaar should always be run as you, not as root.  Solaar distributions should include a udev rule file that allows Solaar to read and write directly to Logitech devices even when run as you.  The code quality of Solaar isn't high enough to run as root and running as root ends up creating configuration files in roots home directory, which is not a good thing.

**Comment by fat-tire** [comment]
Thanks.  Yeah I mean I didn't run it as root ever-- just thought maybe there was some set of alternate configs somewhere had it been run that way.  Also, rereading-- i previously spelled "root" as "rute" I don't know what I was thinking.  I won't file bug reports while on the phone at the same time again, that's for sure :)

No clue how that file was made blank, but thank you for the fix!

**Comment by cyqsimon** [comment]
Thanks for the quick patch. The latest commit fixed my issue.

Similar issue I had on Manjaro after upgrading to 1.1.5; the error was slightly different: `AttributeError: 'NoneType' object has no attribute 'key'`.

The observed symptom was that my custom rules were no longer applied for my MX Anywhere 2s, although there very well might be other issues that I did not notice if this is a configuration-parsing error.

**Comment by pfps** [comment]
@cyqsimon It's good to know that your problem has been fixed.  If  you run into any more problems please create an issue.

**Comment by pfps** [comment]
The AttributeError appears to be the same as #1788.
