### ISSUE TITLE
Logitech K400 missing Fn swap key

### ISSUE THREAD

**Issue by gerroon** [pwr-Solaar/Solaar#564]
Hi

There used to be a swap option for the Fn keys for this models but with one of the recent updates that feature is gone.

Is it possible to still force fn switch?

**Comment by jeroenk-channelengine** [comment]
It looks like it's broken in the current package (at least the one I was using for raspbian), but works again in the master branch.
The solution is to use a clone of the master branch. This is what I used (adapted from https://github.com/pwr-Solaar/Solaar/issues/248#issuecomment-434459351).

```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
sudo ./rules.d/install.sh
sudo python setup.py install --prefix /usr/local  --install-layout deb 
```

**Comment by gerroon** [comment]
@ jeroenk-channelengine 

thanks for teh reply. I did your recommendation and I still do not see the switch for the fn key, as it used to be in the ui. And Fn keys are still switch. Man whoever is invented and inverted this fn keys by default is a friggin moron :(

**Comment by zonay** [comment]
> It looks like it's broken in the current package (at least the one I was using for raspbian), but works again in the master branch.
> The solution is to use a clone of the master branch. This is what I used (adapted from [#248 (comment)](https://github.com/pwr-Solaar/Solaar/issues/248#issuecomment-434459351)).
> 
> ```
> git clone https://github.com/pwr-Solaar/Solaar.git
> cd Solaar
> sudo ./rules.d/install.sh
> sudo python setup.py install --prefix /usr/local  --install-layout deb 
> ```

This method works for me. Thanks!

**Comment by gerroon** [comment]
I have k400r and it still does not work for me

**Comment by FFY00** [comment]
Can you post the output of `solaar show`?

**Comment by gerroon** [comment]
```
solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : B6AD9C6A
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=197

  1: Wireless Touch Keyboard K400
     Codename     : K400
     Kind         : keyboard
     Wireless PID : 4024
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: AF5FF8D5
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).



```

**Comment by FFY00** [comment]
The device needs to be on.

**Comment by gerroon** [comment]
Sorry I was using and SSH session


https://paste.debian.net/hidden/cf266f0f/

**Comment by pfps** [comment]
I just checked on my K400+.  It is slightly different, but it works fine in the current master branch from the repository.  Please download and check this version if you haven't already.  (You should be able to just clone the repository and run bin/solaar from there without doing any install.)
If you have problems with the current version, please try bin/solaar config 1
That will show what the CLI thinks is configurable for the device.
Then try bin/solaar config 1 fn-swap true
(and also false) and see if the value changed.

**Comment by gerroon** [comment]
Hi
I followed your directions to install the new version. I installed the udev rules etc. I then unplugged and plug the unit back.

The device is connected since I am using it to type this.

```
solaar config 1
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw0,3)>> ignored
solaar: error: Logitech receiver not found

```

```
solaar config 1 fn-swap true
solaar: assertion failed: /home/XXX/.local/lib/python2.7/site-packages/logitech_receiver/settings.py line 64

```

**Comment by pfps** [comment]
It looks as if you have 2.7 as your default python.   Solaar was written to work with both 2.7 and 3.x, but I expect that the recent changes haven't been fully vetted in 2.7.
I tried to run solaar under python2.7 but pip2.7 was unable to find a suitable version of python-gi.
As python2.7 is deprecated I don't expect I'll have much luck finding out how to install python-gi for 2.7.

The net result is, I think, to give up on support for python2.7 in solaar.

So please try using python3.  You will probably have to install solaar's dependencies in python3 just like you did for python2.

But the first thing I would try to do is to try to run solaar directly from your download directory, via
python3 bin/solaar
and fixing any missing dependencies via
pip3 install --user <dependency>

**Comment by gerroon** [comment]
thanks I willl give it a go.

**Comment by gerroon** [comment]
Some progress but not so much either.

It is interesting that running `python3 bin/solaar` gives me no error and Is ee the device is listed there.


```

PC:/tmp/Solaar$ python3 bin/solaar config 1                                                                                                                   
solaar: error: Wireless Touch Keyboard K400 is offline                                                                                                                    
PC:/tmp/Solaar$                                                                                                                                               
PC:/tmp/Solaar$                                                                                                                                               
PC:/tmp/Solaar$ python3 bin/solaar config 1
solaar: assertion failed: /tmp/Solaar/lib/logitech_receiver/settings.py line 64
PC:/tmp/Solaar$ python3 bin/solaar config 1
solaar: assertion failed: /tmp/Solaar/lib/logitech_receiver/settings.py line 64
PC:/tmp/Solaar$ python3 bin/solaar config 1 fn-swap true
solaar: assertion failed: /tmp/Solaar/lib/logitech_receiver/settings.py line 64

```

**Comment by pfps** [comment]
OK, it looks as if the problem is that Solaar is trying to check that the features that the  K400 are suitable for it.   The K400 is saying that it is a keyboard (and ignoring the fact that it also has a touchpad).  Solaar lists HI RES SCROLLING as being suitable only for mice and trackballs.
Unless there is a way to determine that the K400 has a touchpad my view is that the assertion should be removed.  @FF00 - any comment on this?
As to why the GUI isn't (so) affected, this check is probably only in code that the CLI uses.
By the way the K400+ doesn't have this problem as it doesn't advertise HI RES SCROLLING.  It has features that look like they should not be for keyboards, but Solaar doesn't implement them.

**Comment by gerroon** [comment]
Ok commenting the assertion gets rid of the errors.

`python3 bin/solaar config 1 fn-swap false` also fixes the FN keys for me, true did not work

**Comment by pfps** [comment]
false should make the keys act like function keys.
true should end up with X11 keys like XF86Music, or whatever.
This should be what is stated in the documentation.

Is that what you are seeing?
If so, that should solve your issue.

**Comment by gerroon** [comment]
Yes "false" is how I was trying to use, like the regular function keys. It drives me nuts to press extra keys to get the function keys :) I do not need multimedia stuff on it.
